pipeline {
	agent { 
  label 'slave1' 
  }
	tools {
	nodejs 'NodeJS'
	}
	stages {
    stage('preparing files') {
  parallel {
		stage('compressing js') {
			steps {
				sh "ls www/js | xargs -I@ uglifyjs -o www/min/@ --compress"
            }
            }
   		stage('compressing css') {
      			steps {
        			sh "ls www/css | xargs -I@ cleancss -o www/min/@"
    }
    }
}
}
	stage('archiving the results') {
		steps {
		sh "tar --exclude=.git --exclude=www/css --exclude=www/js --exclude=Week2_CI_CD_tools/result.tar.gz -czvf Week2_CI_CD_tools/result.tar.gz ."
		archiveArtifacts artifacts: 'Week2_CI_CD_tools/result.tar.gz', fingerprint: true
		}
	}
	stage('pushing to artifactory'){
	    steps{
	        withCredentials([usernamePassword(credentialsId: 'artifactory_jfrog', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
				sh "curl -u${USERNAME}:${PASSWORD} -T result.tar.gz \"http://159.223.17.1:8082/artifactory/material-design-template/build${env.BUILD_NUMBER}.tar.gz\""
	    	}
		}
	}
	}
}

